import { IDish } from '../../types';

const dishes: IDish[] = [
    {
        dishId: 1,
        title: 'Margherita Pizza',
        description: 'Classic pizza with tomato sauce and mozzarella cheese.',
        price: 10.99,
        image: 'https://www.blossmangas.com/wp-content/uploads/2021/05/Margherita-pizza-2.jpg',
        specialities: ['Italian', 'Pizza'],
        isVeg: true,
        ratings: 4.5,
        ingredients: ['Tomato Sauce', 'Mozzarella Cheese', 'Basil', 'Olive Oil'],
    },
    {
        dishId: 2,
        title: 'Pad Thai',
        description: 'Traditional Thai stir-fried noodles with peanuts and lime.',
        price: 12.49,
        image: 'https://inquiringchef.com/wp-content/uploads/2023/02/Authentic-Pad-Thai_square-1908-500x375.jpg',
        specialities: ['Thai', 'Noodles'],
        isVeg: false,
        ratings: 3.5,
        ingredients: ['Rice Noodles', 'Shrimp', 'Tofu', 'Peanuts'],
    },
    {
        dishId: 3,
        title: 'Burger',
        description: 'Juicy beef patty with lettuce, tomato, and special sauce.',
        price: 8.99,
        image: 'https://www.thecookierookie.com/wp-content/uploads/2023/04/featured-stovetop-burgers-recipe.jpg',
        specialities: ['American', 'Burger'],
        isVeg: false,
        ratings: 4.0,
        ingredients: ['Beef Patty', 'Lettuce', 'Tomato', 'Bun'],
    },
    {
        dishId: 4,
        title: 'Sushi Platter',
        description: 'Assortment of fresh sushi rolls and sashimi.',
        price: 18.99,
        image: 'https://www.openfood.co.za/wp-content/uploads/147.jpg',
        specialities: ['Japanese', 'Sushi'],
        isVeg: false,
        ratings: 4.8,
        ingredients: ['Rice', 'Fish', 'Seaweed', 'Soy Sauce'],
    },
    {
        dishId: 5,
        title: 'Caesar Salad',
        description: 'Crisp romaine lettuce with Caesar dressing and croutons.',
        price: 7.49,
        image: 'https://www.noracooks.com/wp-content/uploads/2022/06/vegan-caesar-salad-4-500x500.jpg',
        specialities: ['Salad'],
        isVeg: true,
        ratings: 4.3,
        ingredients: ['Romaine Lettuce', 'Caesar Dressing', 'Croutons', 'Parmesan'],
    },
    {
        dishId: 6,
        title: 'Chicken Tikka Masala',
        description: 'Creamy curry with grilled chicken in tomato sauce.',
        price: 14.99,
        image: 'https://www.licious.in/blog/wp-content/uploads/2020/12/Chicken-Tikka-Masala-min.jpg',
        specialities: ['Indian', 'Curry'],
        isVeg: false,
        ratings: 4.6,
        ingredients: ['Chicken', 'Tomato Sauce', 'Cream', 'Spices'],
    },
    {
        dishId: 7,
        title: 'Miso Soup',
        description: 'Traditional Japanese soup with tofu and seaweed.',
        price: 4.99,
        image: 'https://assets.bonappetit.com/photos/58a6240fa9bc8a7a3f1cfada/1:1/w_3332,h_3332,c_limit/classic-miso-soup.jpg',
        specialities: ['Japanese', 'Soup'],
        isVeg: true,
        ratings: 2.2,
        ingredients: ['Tofu', 'Seaweed', 'Miso Paste', 'Green Onions'],
    },
    {
        dishId: 8,
        title: 'Pasta Carbonara',
        description: 'Creamy pasta with bacon, eggs, and Parmesan cheese.',
        price: 11.49,
        image: 'https://www.modernhoney.com/wp-content/uploads/2023/02/Spaghetti-Carbonara-3-crop-scaled.jpg',
        specialities: ['Italian', 'Pasta'],
        isVeg: false,
        ratings: 4.4,
        ingredients: ['Pasta', 'Bacon', 'Eggs', 'Parmesan Cheese'],
    },
    {
        dishId: 9,
        title: 'Sushi Burrito',
        description: 'Giant sushi roll with various fillings, wrapped in seaweed.',
        price: 13.99,
        image: 'https://healthynibblesandbits.com/wp-content/uploads/2016/02/Sushi-Burrito-FF.jpg',
        specialities: ['Japanese', 'Sushi'],
        isVeg: false,
        ratings: 4.7,
        ingredients: ['Rice', 'Fish', 'Vegetables', 'Seaweed'],
    },
    {
        dishId: 10,
        title: 'Caprese Salad',
        description: 'Fresh mozzarella, tomatoes, and basil drizzled with balsamic.',
        price: 9.49,
        image: 'https://www.cubesnjuliennes.com/wp-content/uploads/2022/08/Caprese-Salad-Recipe.jpg',
        specialities: ['Italian', 'Salad'],
        isVeg: true,
        ratings: 3.5,
        ingredients: ['Mozzarella', 'Tomatoes', 'Basil', 'Balsamic Vinegar'],
    },
    {
        dishId: 11,
        title: 'Steak',
        description: 'Juicy grilled steak with a side of vegetables.',
        price: 20.99,
        image: 'https://www.eatingwell.com/thmb/xvL9kmQJYRV264bxbPqY80nJaYA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/lemon-garlic-steak-and-green-beans-3e85081b45d340caaa6174486b1ca968.jpg',
        specialities: ['American', 'Steak'],
        isVeg: false,
        ratings: 4.8,
        ingredients: ['Steak', 'Seasonings', 'Vegetables', 'Potato'],
    },
    {
        dishId: 12,
        title: 'Veggie Stir-Fry',
        description: 'Assorted vegetables stir-fried in a savory sauce.',
        price: 9.99,
        image: 'https://www.wholesomeyum.com/wp-content/uploads/2020/11/wholesomeyum-how-to-stir-fry-vegetables-vegetable-stir-fry-recipe-list-15.jpg',
        specialities: ['Asian', 'Vegetarian'],
        isVeg: true,
        ratings: 4.3,
        ingredients: ['Assorted Vegetables', 'Sauce', 'Rice'],
    },
    {
        dishId: 13,
        title: 'Fish and Chips',
        description: 'Crispy fried fish with seasoned potato wedges.',
        price: 10.99,
        image: 'https://simply-delicious-food.com/wp-content/uploads/2020/02/Fish-and-chips-4.jpg',
        specialities: ['British', 'Seafood'],
        isVeg: false,
        ratings: 4.4,
        ingredients: ['Fish Fillet', 'Potato', 'Tartar Sauce'],
    },
    {
        dishId: 14,
        title: 'Margherita Pasta',
        description: 'Pasta with fresh tomatoes, mozzarella, and basil.',
        price: 12.99,
        image: 'https://content.hy-vee.com/remote.axd/3f4c2184e060ce99111b-f8c0985c8cb63a71df5cb7fd729edcab.ssl.cf2.rackcdn.com/media/18192/sundried-tomato-salmon-pasta.jpg?v=1&mode=crop&width=875&height=657',
        specialities: ['Italian', 'Pasta'],
        isVeg: true,
        ratings: 2.2,
        ingredients: ['Pasta', 'Tomatoes', 'Mozzarella', 'Basil'],
    },
    {
        dishId: 15,
        title: 'Chicken Caesar Wrap',
        description: 'Grilled chicken, lettuce, and Caesar dressing wrapped in a tortilla.',
        price: 8.99,
        image: 'https://www.yellowblissroad.com/wp-content/uploads/2021/01/Chicken-Caesar-Wraps-social.jpg',
        specialities: ['American', 'Wrap'],
        isVeg: false,
        ratings: 4.0,
        ingredients: ['Grilled Chicken', 'Lettuce', 'Tortilla'],
    },
    {
        dishId: 16,
        title: 'Vegetable Biryani',
        description: 'Fragrant rice cooked with mixed vegetables and spices.',
        price: 13.49,
        image: 'https://www.madhuseverydayindian.com/wp-content/uploads/2022/11/easy-vegetable-biryani.jpg',
        specialities: ['Indian', 'Rice'],
        isVeg: true,
        ratings: 4.6,
        ingredients: ['Rice', 'Mixed Vegetables', 'Spices'],
    },
    {
        dishId: 17,
        title: 'Cheese Platter',
        description: 'Assortment of cheeses with crackers and fruits.',
        price: 15.99,
        image: 'https://www.modernhoney.com/wp-content/uploads/2018/04/How-to-make-the-BEST-Fruit-and-Cheese-Board-141-ed.jpg',
        specialities: ['Appetizer'],
        isVeg: true,
        ratings: 4.7,
        ingredients: ['Cheeses', 'Crackers', 'Fruits'],
    },
    {
        dishId: 18,
        title: 'Shrimp Scampi',
        description: 'Shrimp sautéed in garlic butter and white wine sauce.',
        price: 16.99,
        image: 'https://thecozycook.com/wp-content/uploads/2023/06/Shrimp-Scampi-f.jpg',
        specialities: ['Seafood', 'Italian'],
        isVeg: false,
        ratings: 4.5,
        ingredients: ['Shrimp', 'Garlic Butter', 'White Wine', 'Pasta'],
    },
    {
        dishId: 19,
        title: 'Mushroom Risotto',
        description: 'Creamy risotto with sautéed mushrooms and Parmesan.',
        price: 11.99,
        image: 'https://www.crazyvegankitchen.com/wp-content/uploads/2023/02/mushroom-risotto-recipe.jpeg',
        specialities: ['Italian', 'Rice'],
        isVeg: true,
        ratings: 4.3,
        ingredients: ['Rice', 'Mushrooms', 'Chicken Broth'],
    },
    {
        dishId: 20,
        title: 'Chocolate Lava Cake',
        description: 'Warm chocolate cake with a gooey chocolate center.',
        price: 6.99,
        image: 'https://www.recipetineats.com/wp-content/uploads/2021/02/Chocolate-Lava-Cake_7-SQ.jpg',
        specialities: ['Dessert'],
        isVeg: true,
        ratings: 4.7,
        ingredients: ['Chocolate', 'Flour', 'Eggs', 'Sugar'],
    },
];

export default dishes;
